-- Generated by Oracle SQL Developer Data Modeler 4.0.0.833
--   at:        2015-12-28 17:40:01 CST
--   site:      SQL Server 2008
--   type:      SQL Server 2008

CREATE
  TABLE Callcenter
  (
    id_callcenter INTEGER IDENTITY(1,1) NOT NULL ,
    nombre_callcenter NVARCHAR (100) NOT NULL ,
    telefono_callcenter NVARCHAR (20) ,
	estado tinyint default 1 ,
    CONSTRAINT Callcenter_PK PRIMARY KEY CLUSTERED (id_callcenter)
  )
  ON "default"
GO

CREATE
  TABLE Cliente
  (
    id_cliente INTEGER IDENTITY(1,1) NOT NULL ,
    nombre_cliente NVARCHAR (100) NOT NULL ,
    apellido_cliente NVARCHAR (100) NOT NULL ,
    telefono_cliente NVARCHAR (20) ,
	estado tinyint default 1 ,
    CONSTRAINT Cliente_PK PRIMARY KEY CLUSTERED (id_cliente)
  )
  ON "default"
GO

CREATE
  TABLE Detalle_Factura
  (
    id_detalle_factura INTEGER IDENTITY(1,1) NOT NULL ,
    id_producto_fk     INTEGER NOT NULL ,
    id_factura_fk      INTEGER NOT NULL ,
    cantidad           INTEGER NOT NULL ,
    precio_unidad      DECIMAL (28) NOT NULL ,
    cantidad_total     DECIMAL (28) ,
    CONSTRAINT Detalle_Factura_PK PRIMARY KEY CLUSTERED (id_detalle_factura)
  )
  ON "default"
GO

CREATE
  TABLE Empleado
  (
    id_empleado INTEGER IDENTITY(1,1) NOT NULL ,
    nombre_empleado NVARCHAR (100) ,
    apellido_empleado NVARCHAR (100) NOT NULL ,
    tipo_empleado INTEGER NOT NULL ,
    estado tinyint default 1 ,
    CONSTRAINT Empleado_PK PRIMARY KEY CLUSTERED (id_empleado)
  )
  ON "default"
GO

CREATE
  TABLE Envio
  (
    id_envio         INTEGER IDENTITY(1,1) NOT NULL ,
    id_factura_fk    INTEGER NOT NULL ,
    id_callcenter_fk INTEGER NOT NULL ,
    direccion_envio NVARCHAR (255) NOT NULL ,
    estado tinyint default 1 ,
    CONSTRAINT Envio_PK PRIMARY KEY CLUSTERED (id_envio)
  )
  ON "default"
GO

CREATE
  TABLE Factura
  (
    id_factura     INTEGER IDENTITY(1,1) NOT NULL ,
    fecha_factura  DATETIME ,
    id_cliente_fk  INTEGER NOT NULL ,
    id_farmacia_fk INTEGER NOT NULL ,
    id_empleado_fk INTEGER NOT NULL ,
    estado tinyint default 1 ,
    CONSTRAINT Factura_PK PRIMARY KEY CLUSTERED (id_factura)
  )
  ON "default"
GO

CREATE
  TABLE Producto
  (
    id_producto INTEGER IDENTITY(1,1) NOT NULL ,
    nombre_producto NVARCHAR (100) ,
    disponible_producto INTEGER NOT NULL ,
    img_producto NVARCHAR (MAX) ,
	precio_producto DECIMAL (28) NOT NULL,
    estado tinyint default 1 ,
    CONSTRAINT Producto_PK PRIMARY KEY CLUSTERED (id_producto)
  )
  ON "default"
GO

CREATE
  TABLE Tienda
  (
    id_tienda INTEGER IDENTITY(1,1) NOT NULL ,
    nombre_tienda NVARCHAR (100) NOT NULL ,
    telefono_tienda NVARCHAR (20),
    direccion_tienda NVARCHAR (200) ,
    estado tinyint default 1 ,
    CONSTRAINT Tienda_PK PRIMARY KEY CLUSTERED (id_tienda)
  )
  ON "default"
GO

ALTER TABLE Detalle_Factura
ADD CONSTRAINT Detalle_Factura_Factura_FK FOREIGN KEY
(
id_factura_fk
)
REFERENCES Factura
(
id_factura
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Detalle_Factura
ADD CONSTRAINT Detalle_Factura_Producto_FK FOREIGN KEY
(
id_producto_fk
)
REFERENCES Producto
(
id_producto
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Envio
ADD CONSTRAINT Envio_Callcenter_FK FOREIGN KEY
(
id_callcenter_fk
)
REFERENCES Callcenter
(
id_callcenter
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Envio
ADD CONSTRAINT Envio_Factura_FK FOREIGN KEY
(
id_factura_fk
)
REFERENCES Factura
(
id_factura
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Factura
ADD CONSTRAINT Factura_Cliente_FK FOREIGN KEY
(
id_cliente_fk
)
REFERENCES Cliente
(
id_cliente
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Factura
ADD CONSTRAINT Factura_Empleado_FK FOREIGN KEY
(
id_empleado_fk
)
REFERENCES Empleado
(
id_empleado
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Factura
ADD CONSTRAINT Factura_Tienda_FK FOREIGN KEY
(
id_farmacia_fk
)
REFERENCES Tienda
(
id_tienda
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
